In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('dataset.csv')
df.head()

ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
0  0xcdcd      DEHRES17DEL01                 36.0                      4.2   
1  0xd987      KOCRES16DEL01                 21.0                      4.7   
2  0x2784     PUNERES13DEL03                 23.0                      4.7   
3  0xc8b6     LUDHRES15DEL02                 34.0                      4.3   
4  0xdb64      KNPRES14DEL02                 24.0                      4.7   

   Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0            30.327968             78.046106                   30.397968   
1            10.003064             76.307589                   10.043064   
2            18.562450             73.916619                   18.652450   
3            30.899584             75.809346                   30.919584   
4            26.463504             80.372929                   26.593504   

   Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked  \
0                    78.116106  12-02-2022       21:55             22:10   
1                    76.347589  13-02-2022       14:55             15:05   
2                    74.006619  04-03-2022       17:30             17:40   
3                    75.829346  13-02-2022       09:20             09:30   
4                    80.502929  14-02-2022       19:50             20:05   

   Weather_conditions  Road_traffic_density  Vehicle_condition Type_of_order  \
0                 3.0                   4.0                  2         Snack   
1                 5.0                   3.0                  1          Meal   
2                 4.0                   2.0                  1        Drinks   
3                 4.0                   1.0                  0        Buffet   
4                 3.0                   4.0                  1         Snack   

  Type_of_vehicle  multiple_deliveries  Festival  City  Time_taken (min)  
0      motorcycle                  3.0       0.0   3.0                46  
1      motorcycle                  1.0       0.0   3.0                23  
2         scooter                  1.0       0.0   3.0                21  
3      motorcycle                  0.0       0.0   3.0                20  
4         scooter                  1.0       0.0   3.0                41

In [4]:
print(df['Weather_conditions'].unique())
print(df['Road_traffic_density'].unique())
print(df['Festival'].unique())
print(df['City'].unique())

[3. 5. 4. 2. 1.]
[4. 3. 2. 1.]
[0. 1.]
[3. 2. 1.]


In [5]:
df['Weather_conditions'] = df['Weather_conditions'].replace({'Sunny': 1, 'Cloudy': 1, 'Windy' : 2, 'Fog' : 3, 'Sandstorms' : 4, 'Stormy' : 5})
df['Road_traffic_density'] = df['Road_traffic_density'].replace({'Low' : 1, 'Medium' : 2, 'High' : 3, 'Jam' : 4})
df['Festival'] = df['Festival'].replace({'Yes' : 1, 'No' : 0})
df['City'] = df['City'].replace({'Metropolitian' : 3, 'Urban' : 2, 'Semi-Urban' : 1})

In [6]:
df.columns = df.columns.str.strip()
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)'],
      dtype='object')

In [7]:
df.shape

(38055, 20)

In [8]:
df.dropna(inplace = True)

In [9]:
df.shape

(38055, 20)

In [10]:
df = df[~((df["Restaurant_latitude"] == 0) & (df["Restaurant_longitude"] == 0))]  
df = df[~((df["Delivery_location_latitude"] == 0) & (df["Delivery_location_longitude"] == 0))]  

df.to_csv('dataset.csv', index=False)

In [11]:
columns_to_extract = ["Restaurant_latitude", "Restaurant_longitude", 
                      "Delivery_location_latitude", "Delivery_location_longitude"]
df_selected = df[columns_to_extract]

df_selected.to_csv("output.csv", index=False)

In [12]:
df_outliers = df[
    (df["Restaurant_latitude"] < 6) | (df["Restaurant_latitude"] > 37) |
    (df["Restaurant_longitude"] < 68) | (df["Restaurant_longitude"] > 97) |
    (df["Delivery_location_latitude"] < 6) | (df["Delivery_location_latitude"] > 37) |
    (df["Delivery_location_longitude"] < 68) | (df["Delivery_location_longitude"] > 97)
]
print(df_outliers.shape)  
display(df_outliers.head()) 

(146, 20)


ID Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  \
68    0xc042     AGRRES010DEL01                 34.0                      4.7   
223   0xc044      AGRRES12DEL03                 32.0                      4.7   
895   0xc086     GOARES010DEL03                 20.0                      4.7   
1454  0xc067      BHPRES13DEL02                 39.0                      4.5   
1617  0xc061      KOLRES16DEL01                 25.0                      4.0   

      Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
68             -27.163303             78.057044                   27.233303   
223            -27.165108             78.015053                   27.225108   
895            -15.546594             73.760431                   15.606594   
1454           -23.230791             77.437020                   23.250791   
1617           -22.539129             88.365507                   22.549129   

      Delivery_location_longitude  Order_Date  Time_Orderd Time_Order_picked  \
68                      78.127044  16-02-2022  0.958333333             23:05   
223                     78.075053  13-02-2022        20:55             21:10   
895                     73.820431  13-02-2022  0.833333333             20:10   
1454                    77.457020  13-02-2022        09:15             09:20   
1617                    88.375507  15-02-2022        09:25             09:30   

      Weather_conditions  Road_traffic_density  Vehicle_condition  \
68                   4.0                   1.0                  1   
223                  4.0                   4.0                  2   
895                  1.0                   4.0                  2   
1454                 1.0                   1.0                  0   
1617                 4.0                   1.0                  0   

     Type_of_order Type_of_vehicle  multiple_deliveries  Festival  City  \
68          Drinks         scooter                  0.0       0.0   3.0   
223           Meal         scooter                  1.0       0.0   3.0   
895         Drinks      motorcycle                  1.0       0.0   3.0   
1454          Meal      motorcycle                  1.0       0.0   3.0   
1617        Buffet      motorcycle                  0.0       0.0   3.0   

      Time_taken (min)  
68                  15  
223                 31  
895                 29  
1454                29  
1617                19

In [13]:
df = df.drop(df_outliers.index).reset_index(drop=True)

In [14]:
df.shape

(37909, 20)

In [15]:
print(df.duplicated().sum()) 
print(df.duplicated(subset=["Restaurant_latitude", "Restaurant_longitude", 
                            "Delivery_location_latitude", "Delivery_location_longitude"]).sum()) 

0
33564


In [16]:
df["approx_distance_km"] = ((df["Restaurant_latitude"] - df["Delivery_location_latitude"])**2 + 
                            (df["Restaurant_longitude"] - df["Delivery_location_longitude"])**2)**0.5 * 111  # Rough km estimate

df_weird_distances = df[df["approx_distance_km"] > 500]
print(df_weird_distances.shape)
display(df_weird_distances.head())

(0, 21)


Empty DataFrame
Columns: [ID, Delivery_person_ID, Delivery_person_Age, Delivery_person_Ratings, Restaurant_latitude, Restaurant_longitude, Delivery_location_latitude, Delivery_location_longitude, Order_Date, Time_Orderd, Time_Order_picked, Weather_conditions, Road_traffic_density, Vehicle_condition, Type_of_order, Type_of_vehicle, multiple_deliveries, Festival, City, Time_taken (min), approx_distance_km]
Index: []

[0 rows x 21 columns]

In [17]:
api_input_df = df[["ID", "Restaurant_latitude", "Restaurant_longitude", 
                    "Delivery_location_latitude", "Delivery_location_longitude"]].copy()

api_input_df.to_csv("output.csv", index=False)
print("✅ output.csv saved with order IDs.")
print(api_input_df.shape)

✅ output.csv saved with order IDs.
(37909, 5)


In [18]:
df.reset_index(drop=True, inplace=True)

In [19]:
df = df.copy()
print(df.shape)

(37909, 21)


In [20]:
df = df.reset_index(drop=True)
print(df.shape)

(37909, 21)


In [21]:
api_results_df = pd.read_csv('api_results.csv')

In [22]:
df = df.merge(api_results_df, on="ID", how="left")  

In [23]:
df["distance_m"] /= 1000

In [24]:
df.rename(columns={"distance_m": "distance_km"}, inplace=True)

In [25]:
df['duration_sec'] /= 60
df.rename(columns = {'duration_sec': 'travel_time'}, inplace = True)

In [26]:
df.drop('Delivery_person_ID', axis = 1, inplace = True)
df.drop('Delivery_person_Age', axis = 1, inplace = True)
df.drop('Delivery_person_Ratings', axis = 1, inplace = True)
df.drop('Type_of_order', axis = 1, inplace = True)
df.drop('Type_of_vehicle', axis = 1, inplace = True)

In [27]:
df.head()

ID  Restaurant_latitude  Restaurant_longitude  \
0  0xcdcd            30.327968             78.046106   
1  0xd987            10.003064             76.307589   
2  0x2784            18.562450             73.916619   
3  0xc8b6            30.899584             75.809346   
4  0xdb64            26.463504             80.372929   

   Delivery_location_latitude  Delivery_location_longitude  Order_Date  \
0                   30.397968                    78.116106  12-02-2022   
1                   10.043064                    76.347589  13-02-2022   
2                   18.652450                    74.006619  04-03-2022   
3                   30.919584                    75.829346  13-02-2022   
4                   26.593504                    80.502929  14-02-2022   

  Time_Orderd Time_Order_picked  Weather_conditions  Road_traffic_density  \
0       21:55             22:10                 3.0                   4.0   
1       14:55             15:05                 5.0                   3.0   
2       17:30             17:40                 4.0                   2.0   
3       09:20             09:30                 4.0                   1.0   
4       19:50             20:05                 3.0                   4.0   

   Vehicle_condition  multiple_deliveries  Festival  City  Time_taken (min)  \
0                  2                  3.0       0.0   3.0                46   
1                  1                  1.0       0.0   3.0                23   
2                  1                  1.0       0.0   3.0                21   
3                  0                  0.0       0.0   3.0                20   
4                  1                  1.0       0.0   3.0                41   

   approx_distance_km  travel_time  distance_km  
0           10.988439    28.450000      16.8077  
1            6.279108    13.115000       8.8577  
2           14.127993    18.655000      21.3843  
3            3.139554     8.308333       4.8283  
4           20.407102    24.350000      23.4788

In [34]:
df.to_csv('clean_data.csv')